#
# Makefile for Marvell's framebuffer device driver
#

obj-$(CONFIG_FB_DOVE)          += dovefb_base.o dovefb_gfx.o dovefb_ovly.o dovefb_gpio.o

obj-$(CONFIG_FB_DOVE_DCON)     += dovedcon.o

obj-$(CONFIG_DOVEFB_DISPLAY_MODE)	+=	dovefb_display.o
