#
# Makefile for drivers/telephony
#

obj-$(CONFIG_PHONE) += phonedev.o
obj-$(CONFIG_PHONE_IXJ) += ixj.o
obj-$(CONFIG_PHONE_IXJ_PCMCIA) += ixj_pcmcia.o
obj-$(CONFIG_MV_PHONE) += ../../arch/arm/plat-feroceon/mv_drivers_lsp/mv_phone/
obj-$(CONFIG_MV_PHONE_TEST_MODULE) += ../../arch/arm/plat-feroceon/mv_drivers_lsp/mv_phone/
